"""initial schema (v0.3 ERD)

Revision ID: 16dc750b897a
Revises:
Create Date: 2026-09-08 14:24:17.003437

설계서 6장 ERD(v0.3)를 그대로 옮긴 **최초 마이그레이션**이다.
`alembic revision --autogenerate`가 `app/models/`의 SQLAlchemy 모델(`Base.metadata`)과
빈 DB를 비교해 만든 초안이며, 사람이 손본 것은 리비전 id를 `0001`로 바꾼 것뿐이다.
그래서 아래 `upgrade()` 본문은 모델 정의와 1:1로 대응한다 — 컬럼·제약의 의미가 궁금하면
이 파일보다 `app/models/`와 설계서 6.2절을 보는 편이 빠르다.

만드는 테이블 28개 (6.1절 엔터티 그룹 기준):
- 계정·인증 (3): users, auth_identities, password_reset_tokens
- 팀·참가자 (2): teams, players  ← 회원과 게스트를 한 테이블에 두는 v0.3의 핵심 결정
- 프로필 (3): player_profiles, player_positions, skill_rating_history
- 매니저 판단 (2): manager_rankings, manager_ranking_entries
- 설문 (5): survey_templates, survey_questions, survey_options, survey_responses,
  survey_answers
- 일정 (2): events, event_attendances
- 배정 (5): assignment_runs, assignment_constraints, assignment_candidates,
  assignment_squads, assignment_slots
- 경기 (2): quarters, quarter_lineups
- 피어 평가 (3): post_game_surveys, post_game_votes, chemistry_scores
- 운영 (1): audit_logs

생성 순서는 FK 의존성을 따르므로(참조되는 테이블이 먼저) 6장의 표 순서와는 다르다.
`downgrade()`는 정확히 역순으로 모두 DROP한다.

적용 / 되돌리기 (backend 디렉터리, Postgres가 docker compose로 떠 있는 상태):
    alembic upgrade head       # 이 리비전(현재 유일한 리비전)까지 적용
    alembic downgrade base     # 모든 테이블 삭제 → 빈 DB로 복귀 (데이터도 사라진다)
    alembic current            # 지금 DB가 어느 리비전인지 확인

**이 파일은 더 이상 수정하지 않는다.** 이미 어딘가의 DB에 적용된 리비전을 고치면
그 DB와 코드의 스키마가 조용히 어긋난다. 모델을 바꿨다면 `alembic revision --autogenerate
-m "설명"`으로 **새 리비전(0002, 0003, ...)을 추가**하고, 생성된 초안을 검토해 커밋한다.
(autogenerate는 컬럼 이름 변경을 "삭제+추가"로 인식하는 등 한계가 있으므로 반드시 검토.)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('global_role', sa.Enum('ADMIN', 'USER', name='ck_globalrole', native_enum=False, create_constraint=True, length=10), server_default='USER', nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('birth_year IS NULL OR birth_year BETWEEN 1940 AND 2100', name='ck_users_birth_year'),
    sa.CheckConstraint('height_cm IS NULL OR height_cm BETWEEN 120 AND 250', name='ck_users_height_cm'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('auth_identities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('LOCAL', 'KAKAO', name='ck_authprovider', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('provider_uid', sa.String(length=64), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_uid', name='uq_auth_identities_provider_uid')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('survey_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('section', sa.String(length=1), nullable=False),
    sa.Column('order_no', sa.SmallInteger(), nullable=False),
    sa.Column('question_type', sa.Enum('NUMBER', 'ANCHOR4', 'MULTI', 'ORDINAL', 'SINGLE', name='ck_questiontype', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('max_select', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['survey_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'code', name='uq_survey_questions_code')
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['survey_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'user_id', name='uq_survey_responses_user')
    )
    op.create_index(op.f('ix_survey_responses_user_id'), 'survey_responses', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_code', sa.String(length=8), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ARCHIVED', name='ck_teamstatus', native_enum=False, create_constraint=True, length=10), server_default='PENDING', nullable=False),
    sa.Column('min_members', sa.SmallInteger(), server_default='5', nullable=False),
    sa.Column('home_court', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_code')
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('rsvp_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'DONE', 'CANCELED', name='ck_eventstatus', native_enum=False, create_constraint=True, length=10), server_default='OPEN', nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_team_id'), 'events', ['team_id'], unique=False)
    op.create_table('manager_rankings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('ranked_by', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ranked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_rankings_team_id'), 'manager_rankings', ['team_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('MEMBER', 'GUEST', name='ck_playerkind', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'PLAYER', name='ck_teamrole', native_enum=False, create_constraint=True, length=10), server_default='PLAYER', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LEFT', 'REMOVED', name='ck_playerstatus', native_enum=False, create_constraint=True, length=10), server_default='ACTIVE', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('role_granted_by', sa.BigInteger(), nullable=True),
    sa.Column('merged_into_player_id', sa.BigInteger(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'GUEST') = (user_id IS NULL)", name='ck_players_guest_has_no_user'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_into_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['role_granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_index('ix_players_user_status', 'players', ['user_id', 'status'], unique=False)
    op.create_index('uq_players_team_user', 'players', ['team_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('survey_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('order_no', sa.SmallInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'code', name='uq_survey_options_code')
    )
    op.create_table('assignment_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('executed_by', sa.BigInteger(), nullable=False),
    sa.Column('team_count', sa.SmallInteger(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roster_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_runs_event_id'), 'assignment_runs', ['event_id'], unique=False)
    op.create_table('chemistry_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_a_id', sa.BigInteger(), nullable=False),
    sa.Column('player_b_id', sa.BigInteger(), nullable=False),
    sa.Column('together_quarters', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pref_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('pref_mutual', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('synergy_est', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('synergy_ci_low', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('synergy_ci_high', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('synergy_significant', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('player_a_id < player_b_id', name='ck_chemistry_scores_ordered_pair'),
    sa.ForeignKeyConstraint(['player_a_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_b_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_a_id', 'player_b_id', name='uq_chemistry_scores_pair')
    )
    op.create_index('ix_chemistry_scores_a', 'chemistry_scores', ['player_a_id'], unique=False)
    op.create_index('ix_chemistry_scores_b', 'chemistry_scores', ['player_b_id'], unique=False)
    op.create_table('event_attendances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ATTEND', 'ABSENT', 'PENDING', name='ck_attendancestatus', native_enum=False, create_constraint=True, length=10), server_default='PENDING', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_id', name='uq_event_attendances_player')
    )
    op.create_index('ix_event_attendances_event_status', 'event_attendances', ['event_id', 'status'], unique=False)
    op.create_index(op.f('ix_event_attendances_player_id'), 'event_attendances', ['player_id'], unique=False)
    op.create_table('manager_ranking_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ranking_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('rank_no', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['ranking_id'], ['manager_rankings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ranking_id', 'player_id', name='uq_ranking_entries_player'),
    sa.UniqueConstraint('ranking_id', 'rank_no', name='uq_ranking_entries_rank_no')
    )
    op.create_table('player_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Enum('PG', 'SG', 'SF', 'PF', 'C', name='ck_position', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('can_play', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('preference_rank', sa.SmallInteger(), nullable=True),
    sa.Column('self_rating', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('self_rating IS NULL OR self_rating BETWEEN 1 AND 5', name='ck_player_positions_self_rating'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'position', name='uq_player_positions_player_position')
    )
    op.create_index(op.f('ix_player_positions_player_id'), 'player_positions', ['player_id'], unique=False)
    op.create_table('player_profiles',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('prior_overall', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('prior_source', sa.Enum('SURVEY', 'MANAGER', 'DEFAULT', name='ck_priorsource', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('skill_overall', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('skill_shooting', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('skill_ball_handling', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('skill_passing', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('skill_defense', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('skill_rebound_post', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('skill_stamina', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('skill_confidence', sa.Numeric(precision=3, scale=2), server_default='0', nullable=False),
    sa.Column('quarters_played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cumulative_residual', sa.Numeric(precision=7, scale=2), server_default='0', nullable=False),
    sa.Column('avg_margin_per_quarter', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('peer_vote_score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('skill_confidence BETWEEN 0 AND 1', name='ck_player_profiles_confidence'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('post_game_surveys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('respondent_player_id', sa.BigInteger(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondent_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'respondent_player_id', name='uq_post_game_surveys_respondent')
    )
    op.create_index(op.f('ix_post_game_surveys_event_id'), 'post_game_surveys', ['event_id'], unique=False)
    op.create_table('quarters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('quarter_no', sa.SmallInteger(), nullable=False),
    sa.Column('black_score', sa.SmallInteger(), nullable=False),
    sa.Column('white_score', sa.SmallInteger(), nullable=False),
    sa.Column('duration_min', sa.SmallInteger(), server_default='10', nullable=False),
    sa.Column('recorded_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('black_score >= 0 AND white_score >= 0', name='ck_quarters_score_nonneg'),
    sa.CheckConstraint('duration_min > 0', name='ck_quarters_duration_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'quarter_no', name='uq_quarters_event_no')
    )
    op.create_index(op.f('ix_quarters_event_id'), 'quarters', ['event_id'], unique=False)
    op.create_table('skill_rating_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('SURVEY', 'MANAGER_SORT', 'RESIDUAL', 'PEER_VOTE', 'MANAGER_ADJUST', 'ADMIN_ADJUST', 'MERGE', name='ck_ratingsource', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('before_value', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('after_value', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('delta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_rating_history_player_id'), 'skill_rating_history', ['player_id'], unique=False)
    op.create_table('survey_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('option_id', sa.BigInteger(), nullable=True),
    sa.Column('value_num', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['survey_options.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['survey_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', 'option_id', name='uq_survey_answers_option')
    )
    op.create_table('assignment_candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy', sa.Enum('SKILL', 'CHEMISTRY', 'BALANCED', name='ck_strategy', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_adopted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['assignment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_candidates_run_id'), 'assignment_candidates', ['run_id'], unique=False)
    op.create_index('uq_assignment_candidates_adopted', 'assignment_candidates', ['run_id'], unique=True, postgresql_where=sa.text('is_adopted'))
    op.create_table('assignment_constraints',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('LOCK', 'SEPARATE', 'PIN', name='ck_constrainttype', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('group_no', sa.SmallInteger(), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('squad_no', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("(type IN ('LOCK','SEPARATE') AND group_no IS NOT NULL AND squad_no IS NULL) OR (type = 'PIN' AND squad_no IS NOT NULL AND group_no IS NULL)", name='ck_assignment_constraints_shape'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['assignment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_constraints_run_id'), 'assignment_constraints', ['run_id'], unique=False)
    op.create_table('post_game_votes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.BigInteger(), nullable=False),
    sa.Column('target_player_id', sa.BigInteger(), nullable=False),
    sa.Column('vote_type', sa.Enum('BEST_PERFORMER', 'PLAY_AGAIN', name='ck_votetype', native_enum=False, create_constraint=True, length=15), nullable=False),
    sa.Column('target_side', sa.Enum('SAME_TEAM', 'OPPONENT', name='ck_targetside', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['post_game_surveys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'target_player_id', 'vote_type', name='uq_post_game_votes_target')
    )
    op.create_index(op.f('ix_post_game_votes_target_player_id'), 'post_game_votes', ['target_player_id'], unique=False)
    op.create_table('quarter_lineups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quarter_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.Enum('BLACK', 'WHITE', name='ck_side', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('position', sa.Enum('PG', 'SG', 'SF', 'PF', 'C', name='ck_position', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('raw_margin', sa.SmallInteger(), nullable=False),
    sa.Column('normalized_margin', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id', 'player_id', name='uq_quarter_lineups_player')
    )
    op.create_index(op.f('ix_quarter_lineups_player_id'), 'quarter_lineups', ['player_id'], unique=False)
    op.create_table('assignment_squads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('squad_no', sa.SmallInteger(), nullable=False),
    sa.Column('squad_name', sa.String(length=20), nullable=False),
    sa.Column('avg_skill', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['assignment_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'squad_no', name='uq_assignment_squads_no')
    )
    op.create_table('assignment_slots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('squad_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_position', sa.Enum('PG', 'SG', 'SF', 'PF', 'C', name='ck_position', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['assignment_squads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('squad_id', 'player_id', name='uq_assignment_slots_player')
    )
    op.create_index(op.f('ix_assignment_slots_player_id'), 'assignment_slots', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_slots_player_id'), table_name='assignment_slots')
    op.drop_table('assignment_slots')
    op.drop_table('assignment_squads')
    op.drop_index(op.f('ix_quarter_lineups_player_id'), table_name='quarter_lineups')
    op.drop_table('quarter_lineups')
    op.drop_index(op.f('ix_post_game_votes_target_player_id'), table_name='post_game_votes')
    op.drop_table('post_game_votes')
    op.drop_index(op.f('ix_assignment_constraints_run_id'), table_name='assignment_constraints')
    op.drop_table('assignment_constraints')
    op.drop_index('uq_assignment_candidates_adopted', table_name='assignment_candidates', postgresql_where=sa.text('is_adopted'))
    op.drop_index(op.f('ix_assignment_candidates_run_id'), table_name='assignment_candidates')
    op.drop_table('assignment_candidates')
    op.drop_table('survey_answers')
    op.drop_index(op.f('ix_skill_rating_history_player_id'), table_name='skill_rating_history')
    op.drop_table('skill_rating_history')
    op.drop_index(op.f('ix_quarters_event_id'), table_name='quarters')
    op.drop_table('quarters')
    op.drop_index(op.f('ix_post_game_surveys_event_id'), table_name='post_game_surveys')
    op.drop_table('post_game_surveys')
    op.drop_table('player_profiles')
    op.drop_index(op.f('ix_player_positions_player_id'), table_name='player_positions')
    op.drop_table('player_positions')
    op.drop_table('manager_ranking_entries')
    op.drop_index(op.f('ix_event_attendances_player_id'), table_name='event_attendances')
    op.drop_index('ix_event_attendances_event_status', table_name='event_attendances')
    op.drop_table('event_attendances')
    op.drop_index('ix_chemistry_scores_b', table_name='chemistry_scores')
    op.drop_index('ix_chemistry_scores_a', table_name='chemistry_scores')
    op.drop_table('chemistry_scores')
    op.drop_index(op.f('ix_assignment_runs_event_id'), table_name='assignment_runs')
    op.drop_table('assignment_runs')
    op.drop_table('survey_options')
    op.drop_index('uq_players_team_user', table_name='players', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('ix_players_user_status', table_name='players')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_manager_rankings_team_id'), table_name='manager_rankings')
    op.drop_table('manager_rankings')
    op.drop_index(op.f('ix_events_team_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('teams')
    op.drop_index(op.f('ix_survey_responses_user_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_table('survey_questions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('survey_templates')
    # ### end Alembic commands ###
